import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Ian",
  description: "Generated by create next app",
};

const RootLayout: React.FC = ({ children }) => {
  const menu: MenuItem[] = [
    // { id: 1, name: "About", path: "#" },
    // { id: 2, name: "Projects", path: "#projects" },
    // { id: 3, name: "Blog", path: "#blog" },
    // { id: 4, name: "Contact", path: "#contact" },
  ];

  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar menu={menu} />
        <main className="flex flex-col min-h-[calc(100vh-3.5rem-1px)]">
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
};

export default RootLayout;